cd ~/sanntid/project/
subl main.go
subl fsm/FSM.go
subl network/network.go
subl network/peers/peers.go
subl network/bcast/bcast.go
subl config/config.go
subl elevio/elevator_io.go
subl elevcontroller/elevator_controller.go
subl arbitrator/arbitrator.go
subl orderhandler/order_handler.go
subl timer/timer.go
